/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AbrirJornadaDialog: typeof import('./src/components/Jornadas/AbrirJornadaDialog.vue')['default']
    AbrirTurnoDialog: typeof import('./src/components/Turnos/AbrirTurnoDialog.vue')['default']
    Breadcrum: typeof import('./src/components/Breadcrum.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Carrito: typeof import('./src/components/Mostrador/Carrito.vue')['default']
    CarritoLateral: typeof import('./src/components/totona/CarritoLateral.vue')['default']
    CerrarJornadaDialog: typeof import('./src/components/Jornadas/CerrarJornadaDialog.vue')['default']
    CerrarTurnoDialog: typeof import('./src/components/Jornadas/CerrarTurnoDialog.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    copy: typeof import('./src/components/Clientes/DrawerRegister copy.vue')['default']
    CustomBreadcrumb: typeof import('./src/components/ui/CustomBreadcrumb.vue')['default']
    'CustomBreadcrumb.vue': typeof import('./src/components/CustomBreadcrumb.vue.vue')['default']
    CustomCard: typeof import('./src/components/ui/CustomCard.vue')['default']
    CustomToast: typeof import('./src/components/ui/CustomToast.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogDelete: typeof import('./src/components/ui/DialogDelete.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DrawerEdit: typeof import('./src/components/Clientes/DrawerEdit.vue')['default']
    DrawerRegister: typeof import('./src/components/Clientes/DrawerRegister.vue')['default']
    ErrorJornadaDialog: typeof import('./src/components/Jornadas/ErrorJornadaDialog.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    GridProductos: typeof import('./src/components/Mostrador/GridProductos.vue')['default']
    Header: typeof import('./src/components/ui/Header.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListaProductos: typeof import('./src/components/totona/ListaProductos.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProductosTableGrid: typeof import('./src/components/Productos/ProductosTableGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sidebar: typeof import('./src/components/ui/Sidebar.vue')['default']
    TableGrid: typeof import('./src/components/Clientes/TableGrid.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    KeyFilter: typeof import('primevue/keyfilter')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
