/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrum: typeof import('./src/components/Breadcrum.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CustomBreadcrumb: typeof import('./src/components/ui/CustomBreadcrumb.vue')['default']
    'CustomBreadcrumb.vue': typeof import('./src/components/CustomBreadcrumb.vue.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    DialogDelete: typeof import('./src/components/ui/DialogDelete.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DrawerRegister: typeof import('./src/components/Productos/DrawerRegister.vue')['default']
    Header: typeof import('./src/components/ui/Header.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Popover: typeof import('primevue/popover')['default']
    ProductosTableGrid: typeof import('./src/components/Productos/ProductosTableGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sidebar: typeof import('./src/components/ui/Sidebar.vue')['default']
    TableGrid: typeof import('./src/components/Productos/TableGrid.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
